name: Maven Package and Deploy

on:
  push:
    branches: [ main ]  # Chạy khi push lên nhánh main
  release:
    types: [created]    # Vẫn giữ chạy khi tạo release

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'  # Cập nhật thành Java 21 để khớp với pom.xml
          distribution: 'temurin'
          server-id: github
          settings-path: ${{ github.workspace }}
      - name: Build with Maven
        run: mvn -B clean package --file pom.xml
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: KTra-war
          path: target/KTra-0.0.1-SNAPSHOT.war
      - name: Publish to GitHub Packages Apache Maven
        if: github.event_name == 'release'  # Chỉ publish khi tạo release
        run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
        env:
          GITHUB_TOKEN: ${{ github.token }}