name: Maven Package and Deploy

on:
  push:
    branches: [ main ]
  release:
    types: [created]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Build with Maven
        run: mvn -B clean package --file pom.xml

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: KTra-war
          path: target/KTra-0.0.1-SNAPSHOT.war

      - name: Publish to GitHub Packages
        if: github.event_name == 'release'
        run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Deploy to Tomcat
        if: success() && github.event_name == 'push'
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
          TOMCAT_PATH: ${{ secrets.TOMCAT_PATH }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private.key
          chmod 600 private.key
          scp -i private.key -o StrictHostKeyChecking=no target/KTra-0.0.1-SNAPSHOT.war $SSH_USER@$SSH_HOST:$TOMCAT_PATH/webapps/
          rm -f private.key